---
- hosts: ubuntu
  become: true  # Enable sudo for the tasks
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes  # Update the package cache before installing

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: true

    - name: Upload custom index.html
      copy:
        src: ../webfiles/index.html 
        dest: /var/www/html/index.html  

    - name: Set permissions for index.html
      file:
        path: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
